module.exports = {
    bot: function() {
       return [    
       "cc" ,
       "đồ chó",
       "clon", 
       "đm dm duma",
       "địt" ,
       "chu mỏ lồn" ,
       "súc vật", 
       "Địt tằng tằng" ,
       "mặt lòn" ,
       "xử",
       "Thằng mặt cặc" ,
       "vãi lồn" , 
       "fuck " , 
       "cặc" , 
       "lòn lồn loz lôz lồz" ,
       "coconut pussy",
       "đĩ" ,
       "dis" ,
       "bể đầu" ,
       "dậy thì",
       "l** có gai",
       "đcm, đmcs, đkm, djt" ,
       "Đánh lộn" ,
       "Đá chết họa mi mày giờ",
       "chửi người ta",
       "đmcs" ,
       "cocc",
       "chơi gái phò",
       "Gái ngành",
       "Lần đầu",
       "#ĐMCS, #đmcs" ,
       "thằng con cán bộ" ,
       "đụ má Đụ moá đụ mọe" ,
       "nường" ,
       "dánh" ,
       "ke" ,
       "nốc" ,
       "dốc" ,
       "đốc" ,
       "đò đỏ" ,
       "LẨY THÈ LE TÈ LE" ,
       "nõ" ,
       "lõ" ,
       "nọc cọc chông" ,
       "ngoi đít vịt" ,
       "làm đĩ đỉ",
       "ke , que , buồi , cặc , chông , chim , cò cu" ,
       "ghe",
       "LẸO , Cước Chú" ,
       "such ass" ,
       "what life" ,   
       "Shut up ,  cunt" ,
       "ĐCM" ,
       "tiên sư cha mày" ,
       'mẹ đĩ nợ',
       "Bitch",
       "vcl",
       "Chink",
       "Đù",
       "Đạp mày nát bét",
       "Đéo",
       "Đè bẹp mày",
       "Khinh tao",
       "con cặc",
       "bướm",
       "phò cẩu sanh",
       "khốn nạn",
       "tụi bây",
       "Chink , Dickhead , Haizzz , Dyke , Fag , faggot , Gook , Limey , Motherfucker , Queer , Sucker , Whore , Slut , Drop dead ,  bastard , Dick" ,
       "lột đồ nhau" ,
       "Cộng Sản , Quần Què , #DMCS , Bò Đỏ , con cặc, shut fuck , STFU , #STFU , suck my dick , Penis , Pussy , pussy , Việt Nam Cộng Hoà muôn năm , Đảng Lồn , bợ đít , nâng bi , cái lồn , KHÍ ĐỤ , mặt cặc , pussy face , chó , địt , bú buồi , liếm cu , bú lồn cành cạch , nứng lồn mong manh , quện , đĩ chó , Sấp Mặt Lồn , ưng đụ tao à , cái đĩ mẹ , đá phò , dòng đĩ cốt cách , phò năng , đĩ cộng sản , đĩ cách mạng , nứng lồn , bóng long xiên , địt moẹ moài , lồn , đĩ nứng lồn , chim hưng phấn , nứng lồn mong manh , chịch , bú cu , thông đít , Bash , óc chó , ngu chó , óc lồn , đầu khấc , nứng lồn cộng sản, pussy wet , sục cặc , hột le"];
    }
}