module.exports = {
    bot: function() {
       return [    
       "cc" ,
       "đồ chó",
       "clon", 
       "đm",
       "địt con mẹ" ,
       "địt mẹ" , 
       "chu cái mỏ lồn" ,
       "súc vật", 
       "Địt tằng tằng vào sâu bên trong" ,
       "mặt lòn" ,
       "Thằng mặt cặc" ,
       "vãi lồn" , 
       "fuck " , 
       "cặc" , 
       "lòn lồn loz" ,
       "đĩ" ,
       "dis" ,
       "bể cái đầu" ,
       "đcm, đmcs, đkm, djt" ,
       "Mi đánh lộn không?" ,
       "Đá chết họa mi của mày giờ",
       "đmcs" ,
       "cocc",
       "#ĐMCS, #đmcs" ,
       "thằng con cán bộ" ,
       "đụ má Đụ moá" ,
       "nường" ,
       "dánh" ,
       "ke" ,
       "ghe" ,
       "nốc" ,
       "dốc" ,
       "đốc" ,
       "đò đỏ" ,
       "THÌ LA THÌ LẨY THÈ LE TÈ LE" ,
       "nõ" ,
       "lõ" ,
       "nọc cọc chông" ,
       "ngoi đít vịt" ,
       "ke, que, buồi, cặc, chông, chim, cò cu" ,
       "LẸO, Cước Chú" ,
       "such ass" ,
       "what life" ,   
       "Shut up,  cunt" ,
       "ĐCM" ,
       "tiên sư cha mày" ,
       'mẹ cái con đĩ nợ',
       "Bitch",
       "vcl",
       "Chink",
       "Đù",
       "Đạp mày nát bét",
       "Đéo",
       "Đè bẹp mày",
       "Khinh tao à",
       "cái con cặc",
       "bướm",
       "phò cẩu sanh",
       "Chink, Dickhead, Dyke, Fag, faggot , Gook , Limey , Motherfucker, Queer, Sucker, Whore, Slut, Drop dead,  bastard, Dick" ,
       "lột đồ nhau" ,
       "Cộng Sản, Quần Què, #DMCS, Bò Đỏ, con cặc, shut fuck, STFU, #STFU, suck my dick, Penis, Pussy, pussy, Việt Nam Cộng Hoà muôn năm, Đảng Lồn, bợ đít, nâng bi, cái lồn gì vậy, cái lồn gì thế, mặt cặc, pussy face, chó, địt, bú buồi, liếm cu, bú lồn cành cạch, nứng lồn mong manh, quện, đĩ chó, Sấp Mặt Lồn, ưng đụ tao à, cái đĩ mẹ gì vậy, đá phò, dòng đĩ cốt cách, phò năng, đĩ có học, đĩ cộng sản, đĩ cách mạng, nứng lồn, bóng long xiên, địt moẹ moài, lồn, đĩ nứng lồn, chim hưng phấn, nứng lồn mong manh, chịch, bú cu, thông đít, Bash, óc chó, ngu chó, óc lồn, đầu khấc, nứng lồn cộng sản, pussy wet, sục cặc, hột le"];
    }
}