module.exports = {
    bot: function() {
       return {
        "Thứ phò cẩu":"Câu bị nghi vấn",
        "Con cẩu sanh":"Câu bị nghi vấn",
        "Bươm bướm dối trá không thấy ngượng mồm":"Câu bị nghi vấn",
        "Nhớ gia đình ạ":"Câu bình thường",
        "Bản thân của ngày xưa":"Câu bình thường",
        "Gặt hái được nhiều thành công":"Câu bình thường",
        "May mắn lắm đó nha":"Câu bình thường",
        "Tui nói ông nghe nè, tui yêu ông":"Câu bình thường",
        "Thương em là điều anh không thể ngờ":"Câu bình thường",
        "em muốn uống trà sữa":"Câu bình thường",
        "xịt sữa":"Câu bị nghi vấn",
        "bình thường, cx ko hay chi mấy.":"Câu bình thường",
        "Thay ava chào năm mới cho đỡ mốc":"Câu bình thường",
        "100 là đổi từ 85% ra 85 phần 100 đó bạn":"Câu bình thường",
        "Hay!":"câu bình thường",
        "chính sách trả góp như thế nào ạ ?":"Câu bình thường",
        "Ngầu =))))":"Câu bình thường",
        "vai lolll":"Câu bị nghi vấn",
        "chó":"Câu bị nghi vấn",
        "cười ị":"Câu bị nghi vấn",
        "đĩ mọe mày":"Câu bị nghi vấn",
        "Muốn đụ tui thì thả Haha nha":"Câu bị nghi vấn",
        "Gay porn":"Câu bị nghi vấn",
        "wtf ":"Câu bị nghi vấn",
        "Con đĩ lồn":"Câu bị nghi vấn",
        "Đừng có làm cái lồn như vậy nữa":"Câu bị nghi vấn",
        "t lạy dưới lol t lạy lên":"Câu bị nghi vấn",
        "duma đỉnh":"Câu bị nghi vấn",
        "học để xử mấy mẹ hàng xóm":"Câu bị nghi vấn",
        "quá đáng": "Câu bị nghi vấn",
        "Khỏi sợ cưng, cưng dính chị có cách": "Câu bị nghi vấn",
        "Bitch naneun solo": "Câu bị nghi vấn",
        "Ngành IoT trong chương trình đào tạo của FPoly": "Câu bình thường",
        "Yêu hay không yêu, không yêu hay yêu nói một lời": "Câu bình thường",
        "Tổ cha mi": "Câu bị nghi vấn",
        "Đời tôi là một vườn hoa lá": "Câu bình thường",
        "Chỉ muốn vậy": "Câu bình thường",
        "Bắt đầu chuỗi ngày mang kính": "Câu bình thường",
        "Chó Hoang mà cứ nghĩ mình là Bà Hoàng của xã hội": "Câu bị nghi vấn",
        "Bản chất mày mất dạy": "Câu bị nghi vấn",
        "Ai khóc nỗi đau này": "Câu bình thường",
        "Đã ngu mà còn cố tỏ ra nguy hiểm": "Câu bị nghi vấn",
        "Một khi đã ghét thì chỉ muốn dẫm và đạp cho nát bét là xong. Còn một khi đã khinh, thì chỉ lặng thinh và coi như đéo tồn tại": "Câu bị nghi vấn",
        "Chúng ta ko thể chống lại những thằng ngu bởi vì chúng quá đông và nguy hiểm": "Câu bị nghi vấn",
        "Tao không có gì ngoài điều kiện nghe mi": "Câu bị nghi vấn",
        "Em làm gì đã có người yêu, em đang sợ ế đây này": "Câu bình thường",
        "Mày chết đi sống làm gì nữa": "Câu bị nghi vấn",
        "Chàng trai của em, em yêu anh rất nhiều": "Câu bình thường",
        "Anh không ngại việc ra Hà Nội. Anh chỉ cần có lý do thôi": "Câu bình thường",
        "Cuộc sống mà": "Câu bình thường",
        "Thương thì nói rằng thương nha, đừng ấp úng nữa!": "Câu bình thường",
        "Dân thường chơi đẹp đè bẹp dân chơi": "Câu bị nghi vấn",
        "Chỉ muốn như vậy mãi thôi": "Câu bình thường",
        "Tổ lái": "Câu bình thường",
        "Đen đá không đường nha mấy cưng": "Câu bình thường",
        "Chạy ngay đi": "Câu bình thường",
        "Thanh xuân của anh viết tắt là em đó, yêu em!": "Câu bình thường",
        "Quỳnh ơi! Dượng đây!": "Câu bình thường",
        "Qua những ngày xuân": "Câu bình thường",
        "Thương ai nói đi đừng ngại": "Câu bình thường",
        "Độ ta không độ nàng":"Câu bình thường",
        "Anh không thể biến mùa hạ thành đông nhưng cũng không thể khiến em về bên anh": "Câu bình thường",
        "Những người anh em thiện lành của chúng ta đó": "Câu bị nghi vấn",
        "Lần đầu tiên đi chơi gái":"Câu bị nghi vấn",
        "Đặt chân đến chốn này":"Câu bình thường",
        "Đẹp tuyệt":"Câu bình thường",
        "mẹ cái con đĩ":"Câu bị nghi vấn",
        "Quá hay":"Câu bình thường",
        "Tuổi thơ":"Câu bình thường",
        "Có tour bắt đầu ở đà nẵng ko zậy ad":"Câu bình thường",
        "Đến đà nẵng ăn đặc sản trần":"Câu bình thường",
        "Quà bé ơi":"Câu bình thường",
        "Xinh quá trời ơi chị ơi":"Câu bình thường",
        "KHÍ ĐỤ":"Câu bị nghi vấn",
        "dume y chang":"Câu bị nghi vấn",
        "Giờ l** cũng có gai":"Câu bị nghi vấn",
        "t nghĩ lớp 7 t đi làm đĩ":"Câu bị nghi vấn",
        "Ghét mấy đĩ ảo ghê":"Câu bị nghi vấn",
        "Đừng có xạo lồz":"Câu bị nghi vấn",
        "coconut pussy":"Câu bị nghi vấn",
        "Đụ má bài người ta làm":"Câu bị nghi vấn",
        "bitch giọng mẹ ghe":"Câu bị nghi vấn",
        "dm":"Câu bị nghi vấn",
        "chửi người ta mà mày ziên ghê đĩ":"Câu bị nghi vấn",
        "Haizzz thứ khốn nạn tụi bây":"Câu bị nghi vấn"
       }  
    }
}